-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "laundry_service"."manager" add column "active" boolean
--  null default 'true';
