-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "laundry_service"."product" add column "status" boolean
--  not null default 'true';
