-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "laundry_service"."vendor" add column "active" boolean
--  not null default 'true';
